# Generated by ariadne-codegen
# Source: queries/queries.graphql

from .base_model import BaseModel


class GetWorkspace(BaseModel):
    workspace: "GetWorkspaceWorkspace"


class GetWorkspaceWorkspace(BaseModel):
    id: str
    name: str


GetWorkspace.model_rebuild()
