# Generated by fragment (with the help of ariadne-codegen)
# Source: queries/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import PaymentStatus


class CreatePayment(BaseModel):
    create_payment: Union[
        "CreatePaymentCreatePaymentBadRequestError",
        "CreatePaymentCreatePaymentInternalError",
        "CreatePaymentCreatePaymentPayment",
    ] = Field(alias="createPayment", discriminator="typename__")


class CreatePaymentCreatePaymentBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class CreatePaymentCreatePaymentInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class CreatePaymentCreatePaymentPayment(BaseModel):
    typename__: Literal["Payment"] = Field(alias="__typename")
    client_secret: str = Field(alias="clientSecret")
    status: PaymentStatus


CreatePayment.model_rebuild()
