# Generated by fragment (with the help of ariadne-codegen)
# Source: queries/

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PaymentCurrencyCode, PaymentMode, PaymentStatus


class GetPayment(BaseModel):
    payment: Optional["GetPaymentPayment"]


class GetPaymentPayment(BaseModel):
    id: str
    ik: Any
    amount: Any
    currency: "GetPaymentPaymentCurrency"
    status: PaymentStatus
    type_: Any = Field(alias="type")
    type_version: int = Field(alias="typeVersion")
    mode: PaymentMode
    parameters: Any
    created: Any


class GetPaymentPaymentCurrency(BaseModel):
    code: PaymentCurrencyCode
    name: str
    precision: int


GetPayment.model_rebuild()
GetPaymentPayment.model_rebuild()
