# Generated by fragment (with the help of ariadne-codegen)
# Source: queries/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import LedgerAccountTypes


class InstantiateLedgerAccount(BaseModel):
    instantiate_ledger_account: Union[
        "InstantiateLedgerAccountInstantiateLedgerAccountBadRequestError",
        "InstantiateLedgerAccountInstantiateLedgerAccountInstantiateLedgerAccountResult",
        "InstantiateLedgerAccountInstantiateLedgerAccountInternalError",
    ] = Field(alias="instantiateLedgerAccount", discriminator="typename__")


class InstantiateLedgerAccountInstantiateLedgerAccountBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class InstantiateLedgerAccountInstantiateLedgerAccountInstantiateLedgerAccountResult(
    BaseModel
):
    typename__: Literal["InstantiateLedgerAccountResult"] = Field(alias="__typename")
    ledger_account: (
        "InstantiateLedgerAccountInstantiateLedgerAccountInstantiateLedgerAccountResultLedgerAccount"
    ) = Field(alias="ledgerAccount")


class InstantiateLedgerAccountInstantiateLedgerAccountInstantiateLedgerAccountResultLedgerAccount(
    BaseModel
):
    id: str
    path: str
    name: Optional[str]
    type_: LedgerAccountTypes = Field(alias="type")
    created: Any


class InstantiateLedgerAccountInstantiateLedgerAccountInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


InstantiateLedgerAccount.model_rebuild()
InstantiateLedgerAccountInstantiateLedgerAccountInstantiateLedgerAccountResult.model_rebuild()
