# Generated by fragment (with the help of ariadne-codegen)
# Source: queries/

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import PaymentCurrencyCode, PaymentStatus


class ListPayments(BaseModel):
    ledger: Optional["ListPaymentsLedger"]


class ListPaymentsLedger(BaseModel):
    payments: "ListPaymentsLedgerPayments"


class ListPaymentsLedgerPayments(BaseModel):
    nodes: list["ListPaymentsLedgerPaymentsNodes"]
    page_info: "ListPaymentsLedgerPaymentsPageInfo" = Field(alias="pageInfo")


class ListPaymentsLedgerPaymentsNodes(BaseModel):
    id: str
    ik: Any
    amount: Any
    currency: "ListPaymentsLedgerPaymentsNodesCurrency"
    status: PaymentStatus
    type_: Any = Field(alias="type")
    type_version: int = Field(alias="typeVersion")
    created: Any


class ListPaymentsLedgerPaymentsNodesCurrency(BaseModel):
    code: PaymentCurrencyCode


class ListPaymentsLedgerPaymentsPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")


ListPayments.model_rebuild()
ListPaymentsLedger.model_rebuild()
ListPaymentsLedgerPayments.model_rebuild()
ListPaymentsLedgerPaymentsNodes.model_rebuild()
