# Generated by fragment (with the help of ariadne-codegen)
# Source: queries/

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class GetLedgerAccountBalance(BaseModel):
    ledger_account: Optional["GetLedgerAccountBalanceLedgerAccount"] = Field(
        alias="ledgerAccount"
    )


class GetLedgerAccountBalanceLedgerAccount(BaseModel):
    id: str
    path: str
    balance: Any


GetLedgerAccountBalance.model_rebuild()
