# Generated by fragment (with the help of ariadne-codegen)
# Source: queries/

from typing import Any, ClassVar, Dict, List, Optional, Sequence

from pydantic import model_serializer

from .base_model import BaseModel
from .input_types import (
    AddLedgerEntryInput,
    LedgerEntryConditionInput,
    LedgerEntryGroupInput,
    LedgerEntryInput,
    LedgerEntryTagInput,
    LedgerMatchInput,
)


class TypedLedgerEntry(BaseModel):
    """Base class for a strongly-typed `addLedgerEntries` payload.

    Subclasses declare one field per Schema parameter. The serializer below
    reshapes those flat fields into the nested `AddLedgerEntryInput` the API
    expects, so instances can be passed to `add_ledger_entries` directly.
    """

    ENTRY_TYPE: ClassVar[str] = ""
    TYPE_VERSION: ClassVar[Optional[int]] = None
    # Maps Schema parameter name -> Python field name. These differ only when a
    # parameter is camelCased or collides with a field on this class.
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {}

    ik: Any
    ledger_ik: Any
    posted: Optional[Any] = None
    tags: Optional[List[LedgerEntryTagInput]] = None
    groups: Optional[List[LedgerEntryGroupInput]] = None
    conditions: Optional[List[LedgerEntryConditionInput]] = None

    def entry_parameters(self) -> Dict[str, Any]:
        """The `parameters` payload, keyed by Schema parameter name."""
        return {
            parameter_name: getattr(self, field_name)
            for parameter_name, field_name in self.PARAMETER_FIELDS.items()
            if getattr(self, field_name) is not None
        }

    def to_input(self) -> AddLedgerEntryInput:
        """Convert to the `AddLedgerEntryInput` that `addLedgerEntries` takes."""
        return AddLedgerEntryInput(
            ik=self.ik,
            entry=LedgerEntryInput(
                ledger=LedgerMatchInput(ik=self.ledger_ik),
                type=self.ENTRY_TYPE,
                typeVersion=self.TYPE_VERSION,
                parameters=self.entry_parameters(),
                posted=self.posted,
                tags=self.tags,
                groups=self.groups,
                conditions=self.conditions,
            ),
        )

    @model_serializer
    def serialize(self) -> Dict[str, Any]:
        """Serialize as `AddLedgerEntryInput`, not as this flat model.

        The base client dumps variables with `model_dump(by_alias=True)`, so
        this is what puts the correct shape on the wire.
        """
        return self.to_input().model_dump(by_alias=True, exclude_none=True)


def to_entry_inputs(
    entries: Sequence[TypedLedgerEntry],
) -> List[AddLedgerEntryInput]:
    """Convert typed entries to raw inputs, preserving order.

    `add_ledger_entries` accepts typed entries directly. This is for callers who
    want to inspect or adjust the raw payload first.
    """
    return [entry.to_input() for entry in entries]


# No typed Ledger Entry operations were found in the input queries, so no
# per-entry-type payload models were generated. Add the per-entry-type
# `addLedgerEntry` operations for your Schema to the codegen input directory to
# generate them.
