# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel


class AddLedgerEntries(BaseModel):
    add_ledger_entries: Union[
        "AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesError",
        "AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResult",
        "AddLedgerEntriesAddLedgerEntriesBadRequestError",
        "AddLedgerEntriesAddLedgerEntriesInternalError",
    ] = Field(alias="addLedgerEntries", discriminator="typename__")


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesError(BaseModel):
    typename__: Literal["AddLedgerEntriesError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool
    errors: list["AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesErrorErrors"]


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesErrorErrors(BaseModel):
    ik: Any
    code: str
    message: str
    retryable: bool


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResult(BaseModel):
    typename__: Literal["AddLedgerEntriesResult"] = Field(alias="__typename")
    results: list["AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResults"]


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResults(BaseModel):
    is_ik_replay: bool = Field(alias="isIkReplay")
    entry: "AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsEntry"
    lines: list["AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsLines"]


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsEntry(BaseModel):
    type_: Optional[Any] = Field(alias="type")
    id: str
    ik: str
    posted: Any
    created: Any


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsLines(BaseModel):
    id: str
    amount: Any
    account: "AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsLinesAccount"


class AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsLinesAccount(
    BaseModel
):
    path: str


class AddLedgerEntriesAddLedgerEntriesBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class AddLedgerEntriesAddLedgerEntriesInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


AddLedgerEntries.model_rebuild()
AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesError.model_rebuild()
AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResult.model_rebuild()
AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResults.model_rebuild()
AddLedgerEntriesAddLedgerEntriesAddLedgerEntriesResultResultsLines.model_rebuild()
