# Generated by fragment (with the help of ariadne-codegen)

import time
from typing import Any, Dict, Optional

import httpx
from ariadne_codegen.client_generators.dependencies.async_base_client import (
    AsyncBaseClient,
)

from fragment.client.oauth import fetch_token_async
from fragment.exceptions import MissingArgumentException, MissingTokenException


class AsyncFragmentClient(AsyncBaseClient):
    def __init__(
        self,
        api_url: str = "",
        auth_url: str = "",
        auth_scope: str = "",
        client_id: str = "",
        client_secret: str = "",
        http_client: Optional[httpx.AsyncClient] = None,
    ):
        if api_url == "":
            raise MissingArgumentException("api_url")
        if auth_url == "":
            raise MissingArgumentException("auth_url")
        if auth_scope == "":
            raise MissingArgumentException("auth_scope")
        if client_id == "":
            raise MissingArgumentException("client_id")
        if client_secret == "":
            raise MissingArgumentException("client_secret")
        super().__init__(url=api_url, http_client=http_client)

        self.auth_url = auth_url
        self.expiration_time: Optional[float] = None
        self.token: Optional[Dict[str, Any]] = None
        self.client_id = client_id
        self.client_secret = client_secret
        self.auth_scope = auth_scope

    async def refresh_token(self) -> None:
        now = time.time()
        if self.expiration_time is None or self.expiration_time <= now:
            # Held in a local because `self.token` is declared `dict | None`,
            # so reading the attribute back is not narrowed by the assignment.
            token = await fetch_token_async(
                self.auth_url, self.client_id, self.client_secret, self.auth_scope
            )
            self.token = token
            self.expiration_time = now + token["expires_in"]

    async def execute(
        self,
        query: str,
        operation_name: Optional[str] = None,
        variables: Optional[Dict[str, Any]] = None,
        **kwargs: Any,
    ) -> httpx.Response:
        await self.refresh_token()
        if self.token is None:
            raise MissingTokenException()
        headers = kwargs.get("headers", {})
        kwargs.update(
            headers={
                "Authorization": f'Bearer {self.token["access_token"]}',
                **headers,
            }
        )
        return await super().execute(query, operation_name, variables, **kwargs)
