# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Literal, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import PaymentStatus


class CreatePayment(BaseModel):
    create_payment: Union[
        "CreatePaymentCreatePaymentBadRequestError",
        "CreatePaymentCreatePaymentCreatePaymentResult",
        "CreatePaymentCreatePaymentInternalError",
    ] = Field(alias="createPayment", discriminator="typename__")


class CreatePaymentCreatePaymentBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class CreatePaymentCreatePaymentCreatePaymentResult(BaseModel):
    typename__: Literal["CreatePaymentResult"] = Field(alias="__typename")
    payment: "CreatePaymentCreatePaymentCreatePaymentResultPayment"


class CreatePaymentCreatePaymentCreatePaymentResultPayment(BaseModel):
    client_secret: str = Field(alias="clientSecret")
    status: PaymentStatus


class CreatePaymentCreatePaymentInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


CreatePayment.model_rebuild()
CreatePaymentCreatePaymentCreatePaymentResult.model_rebuild()
