# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from .base_model import BaseModel


class GetWorkspace(BaseModel):
    workspace: "GetWorkspaceWorkspace"


class GetWorkspaceWorkspace(BaseModel):
    id: str
    name: str


GetWorkspace.model_rebuild()
