# Generated by fragment (with the help of ariadne-codegen)
# Source: schema.graphql

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    BalanceUpdateConsistencyMode,
    CurrencyCode,
    CurrencyMode,
    LedgerAccountClearingStatus,
    LedgerAccountTypes,
    LedgerDataMigrationStatus,
    LedgerLinesConsistencyMode,
    LedgerTypes,
    LinkType,
    PostLinesAs,
    SceneEventType,
    SchemaConsistencyMode,
    SchemaLedgerAccountStatus,
    SchemaLedgerEntryStatus,
    SchemaPaymentTypeDirection,
    SchemaPaymentTypeStatus,
    SchemaSystemLineKind,
    TxType,
)


class AddLedgerEntryInput(BaseModel):
    entry: "LedgerEntryInput"
    "The [Ledger Entry](https://fragment.dev/api-reference/api-types#input-types-ledgerentryinput) to add"
    ik: Any
    "The [Idempotency Key](https://fragment.dev/api-reference/api-overview#idempotency) for this Ledger Entry"


class ChartOfAccountsInput(BaseModel):
    """The input for your Chart of Accounts in a Schema."""

    accounts: list["SchemaLedgerAccountInput"]
    "The Ledger Accounts modeled by your Schema. Ledger Accounts may be nested up to a maximum depth of 10."
    default_consistency_config: Optional["LedgerAccountConsistencyConfigInput"] = Field(
        alias="defaultConsistencyConfig", default=None
    )
    "The default consistency configuration for all Ledger Accounts in this Schema. \nIf a Ledger Account does not specify its own consistency configuration, it will use the default values provided here. \n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."
    default_currency: Optional["CurrencyMatchInput"] = Field(
        alias="defaultCurrency", default=None
    )
    "The default currency of each Ledger Account in the Chart Of Accounts.\nIt must be provided if `defaultCurrencyMode` is set to `single`.\nAdditionally, `defaultCurrency` must be omitted if `defaultCurrencyMode` is set to `multi`."
    default_currency_mode: Optional[CurrencyMode] = Field(
        alias="defaultCurrencyMode", default=None
    )
    "The default currency mode of each Ledger Account in the Chart Of Accounts."


class CreateCustomCurrencyInput(BaseModel):
    custom_code: str = Field(alias="customCode")
    "The currency code for custom currencies. It can be up to 36 characters long. This is used for display purposes."
    custom_currency_id: Any = Field(alias="customCurrencyId")
    "The ID for a custom currency. This is specified when creating the custom currency using the [createCustomCurrency](https://fragment.dev/api-reference/api-mutations#createcustomcurrency) mutation. It can be up to 36 characters long."
    name: str
    "A human readable name for the currency (e.g. United States Dollar). This is used for display purposes."
    precision: int
    "The number of decimal places this currency goes to. For example, United States Dollars have a precision of 2 (i.e. 100 cents in a dollar), whereas the Jordanian Dinar has a precision of 3. This is used for display purposes."


class CreateLedgerAccountInput(BaseModel):
    consistency_config: Optional["LedgerAccountConsistencyConfigInput"] = Field(
        alias="consistencyConfig", default=None
    )
    "The consistency configuration for this Ledger Account. This defines how updates to this Ledger Account's balance are handled."
    currency: Optional["CurrencyMatchInput"] = None
    "The currency of this Ledger Account. If this is not set, and `currencyMode` is\nnot set to `multi`, the workspace-level default is used."
    currency_mode: Optional[CurrencyMode] = Field(alias="currencyMode", default=None)
    "If set to `multi`, creates a multi-currency Ledger Account. If set to `single`, creates a single-currency Ledger Account."
    linked_account: Optional["ExternalAccountMatchInput"] = Field(
        alias="linkedAccount", default=None
    )
    "The External Account to link to this Ledger Account."
    name: str
    "The human-readable name of this Ledger Account."
    parent: Optional["LedgerAccountMatchInput"] = None
    "The parent of this Ledger Account."
    type_: Optional[LedgerAccountTypes] = Field(alias="type", default=None)
    "The type of ledger account to create. Required if this is a top-level Ledger Account. If not provided, the type will be inferred from the parent."


class CreateLedgerAccountsInput(BaseModel):
    child_ledger_accounts: Optional[list["CreateLedgerAccountsInput"]] = Field(
        alias="childLedgerAccounts", default=None
    )
    "Ledger Accounts to create as children of this Ledger Account."
    consistency_config: Optional["LedgerAccountConsistencyConfigInput"] = Field(
        alias="consistencyConfig", default=None
    )
    "The consistency configuration for this ledger account. See [Configure consistency](https://fragment.dev/guides/configure-consistency)."
    currency: Optional["CurrencyMatchInput"] = None
    "The currency of this Ledger Account. If this is not set, the workspace level default is used."
    currency_mode: Optional[CurrencyMode] = Field(alias="currencyMode", default=None)
    "The currency mode of this Ledger Account. If this is not set, the workspace level default is used."
    ik: Any
    "The idempotency key for creating this Ledger Account."
    linked_account: Optional["ExternalAccountMatchInput"] = Field(
        alias="linkedAccount", default=None
    )
    "The External Account to link to this Ledger Account. This can only be specified on leaf Ledger Accounts. See [Reconcile payments](https://fragment.dev/guides/reconcile-payments)."
    name: str
    "The name of the Ledger Account."
    parent: Optional["LedgerAccountMatchInput"] = None
    "The parent of this Ledger Account. This is only valid on the top level Ledger Account in the payload."
    type_: Optional[LedgerAccountTypes] = Field(alias="type", default=None)
    "The type of this Ledger Account. This field is only required if this is a root Ledger Account. Otherwise, the type will get inherited from its parent."


class CreateLedgerInput(BaseModel):
    balance_utc_offset: Optional[Any] = Field(alias="balanceUTCOffset", default=None)
    'Use this field to specify a timezone for queries to your Ledger. \n\nWhen aggregating balances, all transactions within a 24 hour period starting at midnight UTC are included in each day. \nYou can specify a different starting hour for balances. For example, use "-08:00" to align balances with Pacific Standard Time. \nBalance queries would then consider the start of each local day to be at 8am UTC the next day in UTC. \nThe default timezone is UTC.'
    name: str
    type_: Optional[LedgerTypes] = Field(alias="type", default=None)


class CreatePaymentInput(BaseModel):
    """EXPERIMENTAL: The Payment to create."""

    parameters: Optional[Any] = None
    "Parameters for the specific Payment Type. Must be a key-value pair of strings. Must be a flat object: nested objects and arrays are rejected."
    type_: Any = Field(alias="type")
    "The type of the Payment. Must be defined in the Schema linked to the Ledger."
    type_version: Optional[int] = Field(alias="typeVersion", default=None)
    "The version of the Payment Type. Defaults to the latest active version."


class CurrencyFilter(BaseModel):
    equal_to: Optional["CurrencyMatchInput"] = Field(alias="equalTo", default=None)
    "Must match the value provided"
    in_: Optional[list["CurrencyMatchInput"]] = Field(alias="in", default=None)
    "Must match one of the values provided. Limited to 100 items maximum."


class CurrencyMatchInput(BaseModel):
    code: CurrencyCode
    "The currency code. This is an [enum type](https://fragment.dev/api-reference/api-types#scalars-and-enums-currencycode)."
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId", default=None)
    "The ID for a custom currency. This is specified when creating the custom currency using the [createCustomCurrency](https://fragment.dev/api-reference/api-mutations#createcustomcurrency) mutation."


class CustomAccountInput(BaseModel):
    currency: Optional["CurrencyMatchInput"] = None
    "The currency of this external account. If this is not set, the workspace level default is used. 'currency' cannot be set if 'currencyMode' is 'multi'."
    currency_mode: Optional[CurrencyMode] = Field(alias="currencyMode", default=None)
    "The currency mode of this external account. If set to multi, creates a multi-currency account."
    external_id: Any = Field(alias="externalId")
    "The ID of this account at the external system. This is used as the idempotency key, within the scope of its Custom Link."
    name: str
    "The name of the account at the external system."


class CustomTxInput(BaseModel):
    account: "ExternalAccountMatchInput"
    amount: Any
    currency: Optional["CurrencyMatchInput"] = None
    "The currency of this tx. Should be set for multi-currency accounts."
    description: str
    external_id: Any = Field(alias="externalId")
    "The ID of this tx at the external system. This is used as the idempotency key, within the scope of its Custom Account."
    posted: Any


class DateFilter(BaseModel):
    equal_to: Optional[Any] = Field(alias="equalTo", default=None)
    in_: Optional[list[Any]] = Field(alias="in", default=None)
    "Must match one of the values provided. Limited to 100 items maximum."
    within: Optional[Any] = None
    'Must fall within the given period. Supports a year (e.g. "2026") or a month (e.g. "2026-05"). To match a specific day, use `equalTo`. Cannot be combined with `withinBalanceUTCOffset`.'
    within_balance_utc_offset: Optional[Any] = Field(
        alias="withinBalanceUTCOffset", default=None
    )
    'Must fall within the given period, taking into account the Ledger\'s `balanceUTCOffset`. Supports a year (e.g. "2026") or a month (e.g. "2026-05"). Cannot be combined with `within`.'


class DateTimeFilter(BaseModel):
    """Filters a timestamp field between two moments in time"""

    after: Optional[Any] = None
    'The timestamp value must be after this moment. Specified in ISO 8601 format e.g "1968-01-01T16:45:00Z"'
    before: Optional[Any] = None
    'The timestamp value must be before this moment. Specified in ISO 8601 format e.g "1968-01-01T16:45:00Z"'


class EntryGroupMatchInput(BaseModel):
    key: Any
    value: Any


class ExternalAccountFilter(BaseModel):
    equal_to: Optional["ExternalAccountMatchInput"] = Field(
        alias="equalTo", default=None
    )
    "Ledger Account must linked to the the specified external account"
    in_: Optional[list["ExternalAccountMatchInput"]] = Field(alias="in", default=None)
    "Ledger Account can be linked to any of the specified external accounts. Limited to 100 items maximum."


class ExternalAccountMatchInput(BaseModel):
    """Specify an External Account by using `id`, or `linkId` and `externalId`."""

    external_id: Optional[str] = Field(alias="externalId", default=None)
    "The external system's ID of the External Account. If this is specified, `linkId` is required. `id` is optional, but will be validated if provided."
    id: Optional[str] = None
    "The FRAGMENT ID of the External Account. If this is specified, both `linkId` and `externalId` are optional, but will be validated if provided."
    link_id: Optional[str] = Field(alias="linkId", default=None)
    "The FRAGMENT ID of the Link the External Account is in. If this is specified, `externalId` is required. `id` is optional, but will be validated if provided."


class GroupBalanceAccountFilter(BaseModel):
    """A filter to query balances of a specific subset of accounts"""

    id: Optional["StringFilter"] = None
    "A filter that must match the account ID"
    path: Optional["StringMatchFilter"] = None
    "A filter that must match the account path. Wildcards ('*') may be used only for template variables, and will only match a single variable each."


class GroupFilter(BaseModel):
    """Filter for finding entries by group membership"""

    all: Optional[list["GroupMatchInput"]] = None
    "Find entries that have ALL of the specified groups. Limited to 10 items maximum."
    equal_to: Optional["GroupMatchInput"] = Field(alias="equalTo", default=None)
    "Find groups that exactly match this group"
    in_: Optional[list["GroupMatchInput"]] = Field(alias="in", default=None)
    "Find groups that match any of these groups"
    key_equal_to: Optional[Any] = Field(alias="keyEqualTo", default=None)
    "Find groups with a specific key"
    key_in: Optional[list[Any]] = Field(alias="keyIn", default=None)
    "Find groups with any of these keys"
    not_: Optional["GroupNotFilter"] = Field(alias="not", default=None)
    "Find groups that do not match this predicate"
    not_equal_to: Optional["GroupMatchInput"] = Field(alias="notEqualTo", default=None)
    "Find groups that do not exactly match this group"
    not_in: Optional[list["GroupMatchInput"]] = Field(alias="notIn", default=None)
    "Find groups that do not match any of these groups"
    not_key_equal_to: Optional[Any] = Field(alias="notKeyEqualTo", default=None)
    "Find groups that do not have a specific key"
    not_key_in: Optional[list[Any]] = Field(alias="notKeyIn", default=None)
    "Find groups that do not have any of these keys"


class GroupInput(BaseModel):
    """A Group in a Schema. Group define sequences of Ledger Entries and can help with reconciliation tasks."""

    description: Optional[Any] = None
    "Human-readable description of the Group."
    key: Any
    "The key of this Group. This combined with its value is a stable, unique identifier for this group."
    reconciliation: Optional["GroupReconciliationParametersInput"] = None
    "The parameters that are used to enable reconciliation abilities in a group."


class GroupMatchInput(BaseModel):
    """Input type for matching a specific group by key and value"""

    key: Any
    "The key of the group to match"
    value: Any
    "The value of the group to match"


class GroupNotFilter(BaseModel):
    """DEPRECATED: Use GroupFilter and notKeyIn or notKeyEqualTo instead. Filter for finding entries that do not match this predicate"""

    key_in: Optional[list[Any]] = Field(alias="keyIn", default=None)
    "DEPRECATED: Find entries that are not members of all of these groups. This is an AND filter."


class GroupReconciliationParametersInput(BaseModel):
    """A set of parameters that are used to enable reconciliation abilities in a group"""

    clearing_account_path: "SchemaLedgerAccountMatchInput" = Field(
        alias="clearingAccountPath"
    )
    "The path to the clearing account for this group. A clearing account is an account that is used to indicate funds that are in transit. Also called a suspense account, pending account, or zero balance account."


class Int96ConditionInput(BaseModel):
    """A condition that must be met on an `Int96` field."""

    eq: Optional[Any] = None
    "Amount must exactly match this value. You may not specify this alongside `gte` or `lte`."
    gte: Optional[Any] = None
    "Amount must be greater than or equal to this value."
    lte: Optional[Any] = None
    "Amount must be less than or equal to this value."


class Int96Filter(BaseModel):
    eq: Optional[Any] = None
    "Must exactly equal this Int96 value"
    gte: Optional[Any] = None
    "Must be greater than or equal to this Int96 value"
    lte: Optional[Any] = None
    "Must be less than or equal to this Int96 value"
    ne: Optional[Any] = None
    "Must not equal this Int96 value"


class LedgerAccountClearingStatusFilter(BaseModel):
    equal_to: Optional[LedgerAccountClearingStatus] = Field(
        alias="equalTo", default=None
    )
    "Results must match the specified clearing account status"


class LedgerAccountConditionInput(BaseModel):
    """A set of conditions that a Ledger Account must meet for an operation to succeed."""

    own_balance: Optional["Int96ConditionInput"] = Field(
        alias="ownBalance", default=None
    )
    "A condition that the ownBalance field must satisfy. Note that this condition always applies to the latest balance, not to balances at a specific date or time. See [Read balances](https://fragment.dev/read-balances) for more on the different types of Ledger Account balances."
    total_balance: Optional["Int96ConditionInput"] = Field(
        alias="totalBalance", default=None
    )
    "A condition that the totalBalance field must satisfy. Note that this condition always applies to the latest balance, not to balances at a specific date or time. See [Read balances](https://fragment.dev/read-balances) for more on the different types of Ledger Account balances."


class LedgerAccountConsistencyConfigInput(BaseModel):
    """The payload configuring the consistency for this Ledger Account.
    See [Configure consistency](https://fragment.dev/guides/configure-consistency)."""

    groups: Optional[list["LedgerAccountGroupConsistencyConfigInput"]] = None
    "The consistency configuration for Ledger Entry Groups affecting this account.\n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."
    lines: Optional[LedgerLinesConsistencyMode] = None
    "If set to `strong`, then a Ledger Account's `lines` updates will be strongly consistent with the API response.\nThis Ledger Account's balance will be updated and available for strongly consistent reads before you receive an API response.\n\nOtherwise if unset or set to `eventual`, `lines` updates are applied asynchronously and may not be immediately reflected in queries.\n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."
    own_balance_updates: Optional[BalanceUpdateConsistencyMode] = Field(
        alias="ownBalanceUpdates", default=None
    )
    "If set to `strong`, then a Ledger Account's `ownBalance` updates will be strongly consistent with the API response.\nThis Ledger Account's balance will be updated and available for strongly consistent reads before you receive an API response.\n\nOtherwise if unset or set to `eventual`, `ownBalance` updates are applied asynchronously and may not be immediately reflected in queries.\n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."
    total_balance_updates: Optional[BalanceUpdateConsistencyMode] = Field(
        alias="totalBalanceUpdates", default=None
    )
    "EXPERIMENTAL: If set to `strong`, then a Ledger Account's `totalBalance` updates will be strongly consistent with the API response.\nThis Ledger Account's balance will be updated and available for strongly consistent reads before you receive an API response.\n\nOtherwise if unset or set to `eventual`, `totalBalance` updates are applied asynchronously and may not be immediately reflected in queries.\n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."


class LedgerAccountDataMigrationsFilterSet(BaseModel):
    account_path: Optional["StringFilter"] = Field(alias="accountPath", default=None)
    "Filter by Ledger Account path."
    status: Optional[LedgerDataMigrationStatus] = None
    "Filter by the status of the data migration."


class LedgerAccountFilter(BaseModel):
    equal_to: Optional["LedgerAccountMatchInput"] = Field(alias="equalTo", default=None)
    "Result must match the specified Ledger Account"
    in_: Optional[list["LedgerAccountMatchInput"]] = Field(alias="in", default=None)
    "Results can match any of specified Ledger Accounts"


class LedgerAccountGroupConsistencyConfigInput(BaseModel):
    """The consistency configuration for a specific Ledger Entry Group in this account."""

    key: Any
    "The group key for this configuration."
    own_balance_updates: BalanceUpdateConsistencyMode = Field(alias="ownBalanceUpdates")
    "If set to `strong`, then Ledger Entry Group `ownBalance`s updates for this account will be strongly consistent with the API response.\nThis Ledger Account's Ledger Entry Group balances will be updated and available for strongly consistent reads before you receive an API response.\n\nOtherwise if unset or set to `eventual`, Ledger Entry Group `ownBalance` updates are applied asynchronously and may not be immediately reflected in queries.\n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."


class LedgerAccountMatchInput(BaseModel):
    """Specify a Ledger Account by using `id` or `path`.

    When specifying a Ledger Account by `path`, you must provide `ledger`."""

    id: Optional[str] = None
    "The FRAGMENT ID of the Ledger Account"
    ledger: Optional["LedgerMatchInput"] = None
    "The Ledger to which this Ledger Account belongs. This is required if you are specifying the Ledger Account by `path`."
    path: Optional[str] = None
    "The unique path of the Ledger Account.\nThis is a slash-delimited string containing the keys of an account and all its direct ancestors."


class LedgerAccountTypeFilter(BaseModel):
    equal_to: Optional[LedgerAccountTypes] = Field(alias="equalTo", default=None)
    "Results must be of the specified Ledger Account type"
    in_: Optional[list[LedgerAccountTypes]] = Field(alias="in", default=None)
    "Results can have any of the specified Ledger Account types"


class LedgerAccountsFilterSet(BaseModel):
    clearing_status: Optional["LedgerAccountClearingStatusFilter"] = Field(
        alias="clearingStatus", default=None
    )
    "Use this to filter Ledger Accounts by their clearing account status"
    earliest_posted: Optional["DateTimeFilter"] = Field(
        alias="earliestPosted", default=None
    )
    "Filter by the earliest posted timestamp across all currencies for clearing accounts. You must also provide clearingStatus in the same filter.\nOnly clearing accounts where the minimum posted timestamp (across all currencies) matches this filter will be included."
    has_parent_ledger_account: Optional[bool] = Field(
        alias="hasParentLedgerAccount", default=None
    )
    "Use this to filter Ledger Accounts by their parent status"
    is_linked_account: Optional[bool] = Field(alias="isLinkedAccount", default=None)
    "Use this to filter Ledger Accounts by their linked status"
    latest_posted: Optional["DateTimeFilter"] = Field(
        alias="latestPosted", default=None
    )
    "Filter by the latest posted timestamp across all currencies for clearing accounts. You must also provide clearingStatus in the same filter.\nOnly clearing accounts where the maximum posted timestamp (across all currencies) matches this filter will be included."
    ledger_account: Optional["LedgerAccountFilter"] = Field(
        alias="ledgerAccount", default=None
    )
    "Use this to filter Ledger Accounts by their ID or path"
    linked_account: Optional["ExternalAccountFilter"] = Field(
        alias="linkedAccount", default=None
    )
    "Use this to filter Ledger Accounts by their external linked account ID"
    parent_ledger_account: Optional["LedgerAccountFilter"] = Field(
        alias="parentLedgerAccount", default=None
    )
    "Use this to filter Ledger Accounts by their parent account IDs"
    path: Optional["StringMatchFilter"] = None
    "A filter that must match the account path. Wildcards ('*') may be used only for template variables, and will only match a single variable each.\nFor example: 'assets-root/accounts-receivable/merchant:*' would match: 'assets-root/accounts-receivable/merchant:1' and 'assets-root/accounts-receivable/merchant:1/child'.\nWildcards may not be used outside of template variables. For example, passing in 'assets-root/*' as a filter is invalid and would raise a GraphQL error."
    type_: Optional["LedgerAccountTypeFilter"] = Field(alias="type", default=None)
    "Use this to filter Ledger Accounts by their type"


class LedgerEntriesFilterSet(BaseModel):
    date: Optional["DateFilter"] = None
    "Use this filter to filter Ledger Entries by their `posted` date."
    group: Optional["GroupFilter"] = None
    "Use this to filter Ledger Entries by groups. The response will include entries that contain or do not contain specific groups."
    is_reversal: Optional[bool] = Field(alias="isReversal", default=None)
    "Use this to filter Ledger Entries that were posted using `reverseLedgerEntry`."
    is_reversed: Optional[bool] = Field(alias="isReversed", default=None)
    "Use this to filter Ledger Entries that have been reversed."
    ledger_entry: Optional["LedgerEntryFilter"] = Field(
        alias="ledgerEntry", default=None
    )
    "Use to filter Ledger Entries by their IDs or IKs."
    posted: Optional["DateTimeFilter"] = None
    "Use this filter to filter Ledger Entries by their `posted` timestamp."
    show_hidden: Optional[bool] = Field(alias="showHidden", default=None)
    "Use this filter to show hidden Ledger Entries."
    tag: Optional["TagFilter"] = None
    "Use this to filter Ledger Entries by tags. The response will include entries that contain tags matching the filter."
    type_: Optional["StringFilter"] = Field(alias="type", default=None)
    "Use this to filter Ledger Entries by type. Ledger Entry types are defined in Schemas."
    type_version: Optional["StringFilter"] = Field(alias="typeVersion", default=None)
    "Use this to filter Ledger Entries by their type version."


class LedgerEntryConditionInput(BaseModel):
    """A set of pre-conditions and post-conditions that a Ledger Account balance must meet for an operation to succeed. You must specify at least one of `precondition` or `postcondition` for each condition."""

    account: "LedgerAccountMatchInput"
    "The Ledger Account that must satisfy the provided conditions."
    currency: Optional["CurrencyMatchInput"] = None
    "For Ledger Accounts in the `multi` currency mode, you must specify the currency of the balance affected by the condition. You only need to specify this field for multi-currency accounts."
    postcondition: Optional["LedgerAccountConditionInput"] = None
    "The conditions that must hold after the operation."
    precondition: Optional["LedgerAccountConditionInput"] = None
    "The conditions that must hold prior to the operation."


class LedgerEntryDataMigrationsFilterSet(BaseModel):
    entry_type: Optional["StringFilter"] = Field(alias="entryType", default=None)
    "Filter by Ledger Entry type."
    status: Optional[LedgerDataMigrationStatus] = None
    "Filter by the status of the data migration."
    type_version: Optional["StringFilter"] = Field(alias="typeVersion", default=None)
    "Filter by Ledger Entry type version."


class LedgerEntryFilter(BaseModel):
    equal_to: Optional["LedgerEntryMatchInput"] = Field(alias="equalTo", default=None)
    "Result must be the specified Ledger Entry."
    in_: Optional[list["LedgerEntryMatchInput"]] = Field(alias="in", default=None)
    "Result can be any of the specified Ledger Entries. Limited to 100 items maximum."


class LedgerEntryGroupBalanceFilter(BaseModel):
    """Filter Ledger Entry Groups by their balance impact on a Ledger Account. If a group has a matching balance for the specified account, the group will be included in the results."""

    account: "GroupBalanceAccountFilter"
    "A Ledger Entry Group will be included in the result if it has a balance for the specified account. If 'account' is the only filter specified, then any non-null balance in any currency will match."
    currency: Optional["CurrencyFilter"] = None
    "A Ledger Entry Group will be included in the result if it has a balance for the specified account in the specified currency. If the 'ownBalance' filter is omitted then any non-null balance will match."
    own_balance: Optional["Int96Filter"] = Field(alias="ownBalance", default=None)
    "A Ledger Entry Group will be included in the result if it has a balance for the specified account that passes the specified value predicate. If the 'currency' filter is omitted then any balance in any currency that passes the predicate will match. If the 'currency' filter is included, the value predicate will only be evaluated against the specified currency. "


class LedgerEntryGroupBalanceFilterSet(BaseModel):
    """Optional filters for querying balances on a Ledger Entry Group."""

    account: Optional["GroupBalanceAccountFilter"] = None
    "Filter to a subset of accounts"
    currency: Optional["CurrencyFilter"] = None
    "Filter to one or more currencies"
    own_balance: Optional["Int96Filter"] = Field(alias="ownBalance", default=None)
    "Filter to only balances in a certain range"


class LedgerEntryGroupInput(BaseModel):
    key: Any
    "The key of this group. Can be up to 128 characters long."
    value: Any
    "The value associated with this group's key. Can be up to 128 characters long."


class LedgerEntryGroupMatchInput(BaseModel):
    key: Any
    ledger: "LedgerMatchInput"
    value: Any


class LedgerEntryGroupsFilterSet(BaseModel):
    balance: Optional["LedgerEntryGroupBalanceFilter"] = None
    "Filter Ledger Entry Groups by their balance impact on a Ledger Account. If a group has a matching balance for the specified account, the group will be included in the results."
    created: Optional["DateTimeFilter"] = None
    "Use to filter Ledger Entry Groups by their created timestamp"
    key: Optional["StringFilter"] = None
    "Use to filter Ledger Entry Groups by their key"
    value: Optional["StringFilter"] = None
    "Use to filter Ledger Entry Groups by their value"


class LedgerEntryInput(BaseModel):
    """Ledger Entries are limited to 30 Ledger Lines."""

    conditions: Optional[list["LedgerEntryConditionInput"]] = None
    "Conditions that must be satisfied to post this Ledger Entry. The Ledger Entry will reject with a BadRequestError if any condition is not met. You can only add a condition on a Ledger Account containing a Line in this Ledger Entry."
    description: Optional[str] = None
    "If specified, will also be used as the description for LedgerLines unless they specify their own description."
    groups: Optional[list["LedgerEntryGroupInput"]] = None
    "Adds this Ledger Entry to this set of Ledger Entry Groups"
    ledger: Optional["LedgerMatchInput"] = None
    "The Ledger to which to post this Ledger Entry. Must be linked to a Schema that defines the provided Ledger Entry type."
    lines: Optional[list["LedgerLineInput"]] = None
    "The Ledger Lines to create as part of this Ledger Entry. This cannot be used with Ledger Entries that have a 'type' i.e.  Ledger Entries defined in the Schema. This can be useful during non-routine operations such as an incident. It is not recommended to use 'lines' during routine operations."
    parameters: Optional[Any] = None
    "Parameters to be included in a templated Ledger Entry. All provided parameters must be present in the typed Ledger Entry within the Schema linked to the provided Ledger."
    posted: Optional[Any] = None
    'ISO 8601 timestamp to post this Ledger Entry e.g. "2021-01-01" or "2021-01-01T16:45:00Z". Will error out if supplied to reconcileTx or createOrder since the transaction timestamp will be used instead'
    tags: Optional[list["LedgerEntryTagInput"]] = None
    "A set of tags attached to this Ledger Entry."
    type_: Optional[str] = Field(alias="type", default=None)
    "The type of the Ledger Entry. Must be defined in the Schema linked to the Ledger specified below."
    type_version: Optional[int] = Field(alias="typeVersion", default=None)
    "Experimental: This field is reserved for an upcoming feature and is not yet supported."


class LedgerEntryMatchInput(BaseModel):
    """Specify a Ledger Entry by using `id`."""

    id: Optional[str] = None
    "The FRAGMENT ID of the Ledger Entry"
    ik: Optional[Any] = None
    "The IK provided to the `addLedgerEntry` mutation or the `ik` field returned from a `reconcileTx` mutation. This is required if you have not provided `id`."
    ledger: Optional["LedgerMatchInput"] = None
    "The FRAGMENT ID of the Ledger to which this Ledger Entry belongs. This is required if you have not provided `id`."


class LedgerEntryTagInput(BaseModel):
    key: Any
    "The key of this tag. Can be up to 128 characters long."
    value: Any
    "The value associated with this tag's key. Can be up to 128 characters long."


class LedgerLineInput(BaseModel):
    account: "LedgerAccountMatchInput"
    "The LedgerAccount this line is being added to"
    amount: Optional[Any] = None
    "A positive amount increases the balance of its LedgerAccount, a negative amount reduces the balance of its LedgerAccount"
    currency: Optional["CurrencyMatchInput"] = None
    "The currency the ledger line is in"
    description: Optional[str] = None
    "If not specified the description from the parent LedgerEntryInput will be used"
    key: Optional[str] = None
    "Optional identifier for Ledger Line. You can filter lines by key using [LedgerLinesFilterSet](https://fragment.dev/api-reference/api-types#filter-types-ledgerlinesfilterset)."
    tags: Optional[list["LedgerEntryTagInput"]] = None
    "A set of tags attached to this Ledger Line."
    tx: Optional["TxMatchInput"] = None
    "Required for reconcileTx to specify the transaction being reconciled, you can specify either the FRAGMENT ID or external ID of the transaction"


class LedgerLineMatchInput(BaseModel):
    """Specify a Ledger Line by using `id`."""

    id: str
    "The FRAGMENT ID of the ledger line"


class LedgerLineTagInput(BaseModel):
    key: Any
    "The key of this tag. Can be up to 128 characters long."
    value: Any
    "The value associated with this tag's key. Can be up to 128 characters long."


class LedgerLinesFilterSet(BaseModel):
    created: Optional["DateTimeFilter"] = None
    "Filter by the created timestamp of the Ledger Line. This is the wall-clock time when the Ledger Line was created."
    currency: Optional["CurrencyFilter"] = None
    "Filter by the currency of the Ledger Line."
    date: Optional["DateFilter"] = None
    "Use this filter to filter Ledger Lines by their `posted` date."
    is_reversal: Optional[bool] = Field(alias="isReversal", default=None)
    "Use this to filter Ledger Lines that were posted to this Ledger Account, using `reverseLedgerEntry`."
    is_reversed: Optional[bool] = Field(alias="isReversed", default=None)
    "Use this to filter Ledger Lines that have been reversed."
    key: Optional["StringFilter"] = None
    "Use this to filter Ledger Lines by key. Ledger Line keys are defined in Schemas."
    ledger_account: Optional["LedgerAccountFilter"] = Field(
        alias="ledgerAccount", default=None
    )
    "Specify which Ledger Account to read lines from. Required when querying lines via `Ledger.lines` without a `path` filter. Not allowed when querying via `LedgerAccount.lines`."
    path: Optional["StringMatchFilter"] = None
    'A filter that string matches the account path. Wildcards (\'*\') can be used to return lines across multiple accounts.\nTo search for all instances of a a Ledger Account template, use the `matches` filter  with an wildcard character in place of the template value e.g. `assets/user:*`. This returns lines from all instances of this template, interleaved by `posted` timestamp.\nTo search for all descendant Ledger Accounts under a given path, use a trailing `/*` in the `matches` filter e.g. `assets/user:user-1>/*`. This returns lines from all descendants at any depth, but not lines from the parent account at `assets/user:user-1>`.\nTo OR multiple `matches` patterns and get a single paginated list, use `matchesAny` — e.g. `matchesAny: ["assets/user:user-1/*", "assets/user:user-2/*"]` returns descendants of both prefixes interleaved by `posted` timestamp.\nCannot be combined with `ledgerAccount` filter. Not allowed when querying via `LedgerAccount.lines`. You cannot use wildcards for both descendant and template instance matching in the same query.'
    posted: Optional["DateTimeFilter"] = None
    "Use this filter to filter Ledger Lines by their `posted` timestamp."
    show_hidden: Optional[bool] = Field(alias="showHidden", default=None)
    "Use this filter to find hidden Ledger Lines."
    tag: Optional["TagFilter"] = None
    "Filter Ledger Lines by tag. Only matches lines that have the specified tags attached directly to them."
    type_: Optional["TxTypeFilter"] = Field(alias="type", default=None)


class LedgerMatchInput(BaseModel):
    """Specify a Ledger by using `id` or `ik`."""

    id: Optional[str] = None
    "The FRAGMENT ID of the Ledger"
    ik: Optional[Any] = None
    "The IK passed into the [createLedger](/api-reference/api-mutations#createledger) mutation. This is treated as a second unique identifier for this Ledger."


class LedgerTypeFilter(BaseModel):
    equal_to: Optional[LedgerTypes] = Field(alias="equalTo", default=None)
    in_: Optional[list[LedgerTypes]] = Field(alias="in", default=None)
    "Must match one of the values provided. Limited to 100 items maximum."


class LedgersFilterSet(BaseModel):
    has_schema: Optional[bool] = Field(alias="hasSchema", default=None)
    type_: Optional["LedgerTypeFilter"] = Field(alias="type", default=None)


class LinkMatchInput(BaseModel):
    id: str


class MigrateLedgerEntryInput(BaseModel):
    """An object defining the input for migrating a Ledger Entry."""

    id: str
    "The Ledger Entry to migrate"
    new_ledger_entry: "LedgerEntryInput" = Field(alias="newLedgerEntry")
    "The Ledger Entry you want to migrate it to"


class SceneEntryInput(BaseModel):
    """A simulated Ledger Entry posted as a part of a Scene."""

    parameters: Optional[Any] = None
    "Any parameters to be used as inputs to this simulated Ledger Entry."
    type_: Any = Field(alias="type")
    "The type of the simulated Ledger Entry. Must match one of the types provided in schema.ledgerEntries.types."
    type_version: Optional[int] = Field(alias="typeVersion", default=None)
    "The version of the Ledger Entry type."


class SceneEventInput(BaseModel):
    entry: "SceneEntryInput"
    "The simulated Ledger Entry."
    event_type: SceneEventType = Field(alias="eventType")
    "The type of the Scene Event. Currently, only entries are supported."


class SceneInput(BaseModel):
    events: list["SceneEventInput"]
    "A list of simulated ledger entries that make up the Scene."
    name: str
    "The human-readable name of the Scene."


class SchemaConditionInput(BaseModel):
    """A condition that must be met on a Ledger Account balance. The condition can be
    either a `precondition` or `postcondition`."""

    own_balance: Optional["SchemaInt96ConditionInput"] = Field(
        alias="ownBalance", default=None
    )
    "A condition on the `ownBalance` of the Ledger Account."
    total_balance: Optional["SchemaInt96ConditionInput"] = Field(
        alias="totalBalance", default=None
    )
    "A condition on the `totalBalance` of the Ledger Account."


class SchemaConsistencyConfigInput(BaseModel):
    """The consistency configuration for entities created within Ledgers created by this Schema.

    See [Configure consistency](https://fragment.dev/guides/configure-consistency)."""

    entries: Optional[SchemaConsistencyMode] = None
    "The consistency mode for the Ledger Entries list query within Ledgers created by this Schema.\n\nSee [Configure consistency](https://fragment.dev/guides/configure-consistency)."


class SchemaCurrencyMatchInput(BaseModel):
    """Matches a Currency. Can be a built-in [CurrencyCode](https://fragment.dev/api-reference/api-types#scalars-and-enums-currencycode), custom Currency, or a parameterized string.
    If you supply a parameterized string, you must pass in a valid CurrencyCode as a parameter when posting a Ledger Entry.
    """

    code: Any
    "The currency code. This must either be a [CurrencyCode](https://fragment.dev/api-reference/api-types#scalars-and-enums-currencycode) or a parameterized string that resolves to a CurrencyCode ."
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId", default=None)
    "The ID for a custom currency. This is specified when creating the custom currency using the [createCustomCurrency](https://fragment.dev/api-reference/api-mutations#createcustomcurrency) mutation."


class SchemaExternalAccountMatchInput(BaseModel):
    external_id: Optional[Any] = Field(alias="externalId", default=None)
    "The External systems's ID of the account"
    id: Optional[Any] = None
    "The FRAGMENT ID of the external account"
    link_id: Optional[Any] = Field(alias="linkId", default=None)
    "The FRAGMENT ID of the link"
    link_type: Optional[LinkType] = Field(alias="linkType", default=None)
    "The type of Link this external account belongs to. Must be one of: IncreaseLink, UnitLink, CustomLink, or StripeLink."


class SchemaInput(BaseModel):
    """Input to the API for creating a Schema."""

    chart_of_accounts: "ChartOfAccountsInput" = Field(alias="chartOfAccounts")
    "The Chart of Accounts for the Schema."
    consistency_config: Optional["SchemaConsistencyConfigInput"] = Field(
        alias="consistencyConfig", default=None
    )
    "The consistency configuration for this Schema."
    groups: Optional[list["GroupInput"]] = None
    "Any groups associated with this Schema."
    key: Any
    "The key of the Schema. This is a stable, unique identifier for the Schema. Uniqueness is enforced at the Workspace level."
    ledger_entries: Optional["SchemaLedgerEntriesInput"] = Field(
        alias="ledgerEntries", default=None
    )
    "The Ledger Entries to add to the Schema."
    name: Optional[Any] = None
    "The human-readable name of the Schema."
    payments: Optional["SchemaPaymentsInput"] = None
    "EXPERIMENTAL: The Payment Types to add to the Schema."
    scenes: Optional[list["SceneInput"]] = None
    "Any scenes associated with this Schema."


class SchemaInt96ConditionInput(BaseModel):
    """A condition that must be met on a field."""

    eq: Optional[Any] = None
    "Amount must be exactly equal to this value. You may not specify this alongside `gte` or `lte`."
    gte: Optional[Any] = None
    "Amount must be greater than or equal to this value."
    lte: Optional[Any] = None
    "Amount must be less than or equal to this value."


class SchemaLedgerAccountInput(BaseModel):
    """Models a Ledger Account in a Schema.
    Upon successfully storing a [Schema](https://fragment.dev/api-reference/api-types#core-types-schema), a [LedgerAccount](https://fragment.dev/api-reference/api-types#core-types-ledgeraccount) will be created for
    each corresponding non-templated `SchemaLedgerAccountInput` in your Chart of Accounts.
    """

    children: Optional[list["SchemaLedgerAccountInput"]] = None
    "Ledger Accounts to create as children of this Ledger Account. Ledger Accounts may be nested up to a maximum depth of 10."
    clearing: Optional[bool] = None
    "EXPERIMENTAL: Whether or not this Ledger Account is a Clearing Account.\nClearing Accounts have balances that should tend to zero. They are used to track in-progress workflows and payments."
    consistency_config: Optional["LedgerAccountConsistencyConfigInput"] = Field(
        alias="consistencyConfig", default=None
    )
    "The consistency configuration for this ledger account. See [Configure consistency](https://fragment.dev/guides/configure-consistency)."
    currency: Optional["SchemaCurrencyMatchInput"] = None
    "The currency of this Ledger Account. If this is not set, and `currencyMode` is\nnot set to `multi`, it is derived from the Chart of Accounts' default."
    currency_mode: Optional[CurrencyMode] = Field(alias="currencyMode", default=None)
    "If set to `multi`, creates a multi-currency Ledger Account. If set to `single`, creates a single-currency Ledger Account."
    key: Any
    "The key of this Ledger Account. Keys are used to formulate the unique path of the Ledger Account in your Chart of Accounts.\nSiblings must have unique keys."
    linked_account: Optional["SchemaExternalAccountMatchInput"] = Field(
        alias="linkedAccount", default=None
    )
    "The External Account to link to this Ledger Account.\nIt must be provided of `linked` is true."
    name: Optional[Any] = None
    "The human-readable name of this Ledger Account."
    payment: Optional["SchemaPaymentInput"] = None
    "EXPERIMENTAL: Marks this as a Payment Account."
    status: Optional[SchemaLedgerAccountStatus] = None
    "The status of this Ledger Account. Defaults to active."
    template: Optional[bool] = None
    "Whether or not this Ledger Account should be templated."
    type_: Optional[LedgerAccountTypes] = Field(alias="type", default=None)
    "The type of ledger account to create. Required if this is a top-level Ledger Account. If not provided, the type will be inferred from the parent."


class SchemaLedgerAccountMatchInput(BaseModel):
    """Matches a Ledger Account in a Schema."""

    path: Any
    'The unique path of the Ledger Account in the Schema.\nThis is a slash-delimited string containing the keys of a Ledger Account and all its direct ancestors.\nex: expense-root/subscriptions/netflix\nFor Templated Ledger Accounts, you must supply a parameter in the path that will be used to name an instance of the template.\nex: `"expense-root/subscriptions/vendor:{{vendor_name}}"`'


class SchemaLedgerEntriesInput(BaseModel):
    """The Ledger Entries in your Schema."""

    types: list["SchemaLedgerEntryInput"]
    "A list of Ledger Entry definitions."


class SchemaLedgerEntryConditionInput(BaseModel):
    """A condition that must be met on a Ledger Account when a Ledger Entry is posted."""

    account: "SchemaLedgerAccountMatchInput"
    "The Ledger Account to apply the condition to."
    currency: Optional["SchemaCurrencyMatchInput"] = None
    "The currency of the balance to apply the condition to. Required if the Ledger Account matched is a multi-currency Ledger Account.\nOtherwise, this field is defaults to the Ledger Account's currency."
    postcondition: Optional["SchemaConditionInput"] = None
    "A `postcondition` must be met after the Ledger Entry updates are applied."
    precondition: Optional["SchemaConditionInput"] = None
    "A `precondition` must be met before any Ledger Entry updates are applied."
    repeated: Optional["SchemaRepeatedConfigInput"] = None
    "Repeated expansion configuration. When set, this condition is expanded at runtime for each element\nin the array parameter named by the key."


class SchemaLedgerEntryGroupInput(BaseModel):
    """A Ledger Entry Group associated with a Ledger Entry type."""

    key: Any
    "The key for this Ledger Entry Group."
    value: Any
    "The value associated with this Ledger Entry Group."


class SchemaLedgerEntryInput(BaseModel):
    """A Ledger Entry in a Schema. All Ledger Entries defined in a Schema must have a unique `type`."""

    conditions: Optional[list["SchemaLedgerEntryConditionInput"]] = None
    "Conditions that must be satisfied to post this Ledger Entry. The Ledger Entry will reject with a BadRequestError if any condition is not met. You can only add a condition on a Ledger Account containing a Line in this Ledger Entry."
    description: Optional[Any] = None
    "Human-readable description of the Ledger Entry."
    groups: Optional[list["SchemaLedgerEntryGroupInput"]] = None
    "Ledger Entries posted with this type will be in these Ledger Entry Groups."
    lines: Optional[list["SchemaLedgerLineInput"]] = None
    "The Ledger Lines in the Ledger Entry.\nIf provided, when posting a Typed Entry, a [LedgerEntry](https://fragment.dev/api-reference/api-types#core-types-ledgerline) will be posted containing [LedgerLines](https://fragment.dev/api-reference/api-types#core-types-ledgerline) corresponding\nto the values you provide here. If your lines contain parameters, you must supply values for those parameters that balance out the Ledger Entry. If not provided, lines will be required when posting a Typed Entry."
    parameters: Optional[Any] = None
    "Fixed partial set of parameters to be included in a templated Ledger Entry."
    post_lines_as: Optional[PostLinesAs] = Field(alias="postLinesAs", default=None)
    "Controls how lines are posted. When set to `net_amounts`, all lines targeting the same account, currency, and tx are aggregated into a single line with the net amount, and lines that sum to zero are skipped. When set to `skip_zero_lines`, lines with a zero amount are skipped but not aggregated. In both modes, if all lines are zero, no lines are skipped. When set to `raw_lines`, lines are posted as-is without aggregation. New entries created via the dashboard default to `net_amounts`. Existing entries without this field set are treated as `raw_lines`."
    status: Optional[SchemaLedgerEntryStatus] = None
    "The status of this Ledger Entry. Defaults to active."
    tags: Optional[list["SchemaLedgerEntryTagInput"]] = None
    "Ledger Entries posted with this type will be associated with these tags."
    type_: Any = Field(alias="type")
    "The type of this Ledger Entry. This is a stable, unique identifier for this entry. Uniqueness is enforced at the Schema level.\nYou can filter on this field when querying for Ledger Entries. See the docs on [LedgerEntryFilterSet](https://fragment.dev/api-reference/api-types#filter-types-ledgerentriesfilterset)"
    type_version: Optional[int] = Field(alias="typeVersion", default=None)
    "The version of the Ledger Entry type."


class SchemaLedgerEntryTagInput(BaseModel):
    """A tag associated with a Ledger Entry type."""

    key: Any
    "The key for this tag."
    value: Any
    "The value associated with the given key for this tag."


class SchemaLedgerLineInput(BaseModel):
    """A Ledger Line in a Ledger Entry."""

    account: "SchemaLedgerAccountMatchInput"
    "The Ledger Account this Ledger Line will be posted to.\nIt supports parameters in its attributes via handlebars syntax."
    amount: Optional[Any] = None
    "The amount of the Ledger Line. It supports parameters via the handlebars syntax and addition (+) and subtraction (-)."
    currency: Optional["SchemaCurrencyMatchInput"] = None
    "The currency of the Ledger Line. This is required if the Ledger Account has currencyMode multi.\nIt supports parameters in its attributes via handlebars syntax."
    description: Optional[Any] = None
    "Human-readable description of the line."
    key: Any
    "The key for the Ledger Line. Ledger Line keys must be unique within a Ledger Entry. Key can be filtered on as part of the LedgerLinesFilterSet."
    repeated: Optional["SchemaRepeatedConfigInput"] = None
    "Repeated expansion configuration. When set, this line is expanded at runtime for each element\nin the array parameter named by the key."
    tags: Optional[list["SchemaLedgerEntryTagInput"]] = None
    "Tags to attach to this Ledger Line. Supports parameterized values via handlebars syntax."
    tx: Optional["SchemaTxMatchInput"] = None
    "The external transaction to reconcile.\nThis field is required if the Ledger Account being posted to is a Linked Ledger Account. Otherwise, this field is disallowed.\nIt supports parameters in its attributes via handlebars syntax.\n\nSee the docs on [reconciling payments](https://fragment.dev/guides/reconcile-payments)."


class SchemaMatchInput(BaseModel):
    """An object used to retrieve a Schema."""

    key: Any
    "The key to retrieve a Schema by.\n`key` is unique to a Workspace."
    version: Optional[int] = None
    "Optional parameter to specify version of requested Schema. If not provided, it defaults to 0, representing the latest available version for the provided Schema key."


class SchemaPaymentAccountingInput(BaseModel):
    """EXPERIMENTAL: The Ledger Entries a Payment Type posts as a payment moves
    through its lifecycle, keyed by lifecycle transition."""

    needs_payment_method_to_processing: Optional["SchemaPaymentEntryInput"] = None
    "Posted when the payment enters processing. Optional."
    processing_to_settled: "SchemaPaymentEntryInput"
    "Posted when the payment settles. Every Payment Type must define it."


class SchemaPaymentEntryInput(BaseModel):
    """EXPERIMENTAL: The Ledger Entry a Payment Type posts on a payment lifecycle event."""

    description: Optional[Any] = None
    "Human-readable description of the payment entry."
    lines: list["SchemaPaymentLineInput"]
    "The Ledger Lines in the payment entry."


class SchemaPaymentInput(BaseModel):
    """EXPERIMENTAL: Marks a Ledger Account as a Payment Account."""

    penguin: bool


class SchemaPaymentLineInput(BaseModel):
    """EXPERIMENTAL: A Ledger Line in a payment entry."""

    account: "SchemaLedgerAccountMatchInput"
    "The Ledger Account this line will be posted to.\nIt supports parameters in its attributes via handlebars syntax."
    amount: Any
    "The amount of the line. It supports parameters via the handlebars syntax and addition (+) and subtraction (-)."
    currency: Optional["SchemaCurrencyMatchInput"] = None
    "The currency of the line. This is required if the Ledger Account has currencyMode multi.\nIt supports parameters in its attributes via handlebars syntax."
    description: Optional[Any] = None
    "Human-readable description of the line."
    key: Any
    "The key for the line. Keys must be unique within a payment entry."
    system: Optional[SchemaSystemLineKind] = None
    "Marks this as a system-owned line. Fragment fills the amounts of system\nlines when the payment entry is posted."


class SchemaPaymentTypeDetailsInput(BaseModel):
    """EXPERIMENTAL: The payment a Payment Type creates."""

    amount: Any
    "The amount requested for the payment, as a parameterized expression filled\nfrom createPayment parameters."
    direction: SchemaPaymentTypeDirection
    "The direction the payment moves money."


class SchemaPaymentTypeInput(BaseModel):
    """EXPERIMENTAL: A Payment Type in a Schema. All Payment Types defined in a
    Schema must have a unique `type` and `typeVersion` pair."""

    accounting: "SchemaPaymentAccountingInput"
    "The Ledger Entries posted as the payment moves through its lifecycle."
    payment: "SchemaPaymentTypeDetailsInput"
    "The payment this Payment Type creates."
    status: SchemaPaymentTypeStatus
    "The status of this Payment Type."
    type_: Any = Field(alias="type")
    "The type of this Payment Type. This is a stable, unique identifier for it.\nUniqueness is enforced at the Schema level."
    type_version: int = Field(alias="typeVersion")
    "The version of the Payment Type."


class SchemaPaymentsInput(BaseModel):
    """EXPERIMENTAL: The Payment Types in your Schema."""

    types: list["SchemaPaymentTypeInput"]
    "A list of Payment Type definitions."


class SchemaRepeatedConfigInput(BaseModel):
    """Configuration for repeated expansion of a line or condition. The key names a client-supplied
    array parameter whose elements each generate one copy of the line or condition at runtime.
    """

    key: Any
    "The key of the array parameter whose elements expand this line or condition."


class SchemaTxMatchInput(BaseModel):
    """Matches a transaction at an external system.
    This is used to specify the transaction being reconciled into a Linked Ledger Account
    """

    external_id: Optional[Any] = Field(alias="externalId", default=None)
    "The external system's ID for the transaction."
    id: Optional[Any] = None
    "The FRAGMENT ID for the transaction."


class StringFilter(BaseModel):
    equal_to: Optional[str] = Field(alias="equalTo", default=None)
    in_: Optional[list[str]] = Field(alias="in", default=None)
    "Must match one of the values provided. Limited to 100 items maximum."
    not_equal_to: Optional[str] = Field(alias="notEqualTo", default=None)
    "Must not equal this string value"
    not_in: Optional[list[str]] = Field(alias="notIn", default=None)
    "Must not match any of the values provided. Limited to 100 items maximum."


class StringMatchFilter(BaseModel):
    contains: Optional[str] = None
    "Must contain the provided pattern somewhere within the string. For example, 'contains: hat' will match 'hat', 'chat', and 'hate'."
    equal_to: Optional[str] = Field(alias="equalTo", default=None)
    "Must exactly equal the provided value"
    in_: Optional[list[str]] = Field(alias="in", default=None)
    "Must exactly equal one of the provided values. Limited to 100 items maximum."
    matches: Optional[str] = None
    'Must match the provided pattern. Wildcards ("*") will match any substring'
    matches_any: Optional[list[str]] = Field(alias="matchesAny", default=None)
    "Must match any one of the provided `matches` patterns, OR-ed together — results are returned as a single paginated list. Each entry uses the same wildcard grammar as `matches`. Cannot be combined with `matches`. Limited to 100 entries."


class TagFilter(BaseModel):
    """Filters a result set based on the tags it contains."""

    all: Optional[list["TagMatchInput"]] = None
    "Matches entries that have ALL of the specified tags. The key and value are both matched exactly. Limited to 10 items maximum."
    contains: Optional["TagMatchInput"] = None
    "Matches tag values based on the existence of the provided string within the tag value. The key is matched exactly."
    equal_to: Optional["TagMatchInput"] = Field(alias="equalTo", default=None)
    "Matches tags based on the exact value provided. The key and value are both matched exactly."
    in_: Optional[list["TagMatchInput"]] = Field(alias="in", default=None)
    "Matches tags based on a list of possible tag matches. The key and value are both matched exactly. Limited to 100 items maximum."
    key_equal_to: Optional[Any] = Field(alias="keyEqualTo", default=None)
    "Matches tags where the key exactly equals the provided value."
    key_in: Optional[list[Any]] = Field(alias="keyIn", default=None)
    "Matches tags where the key matches any of the provided values. Limited to 100 items maximum."
    not_equal_to: Optional["TagMatchInput"] = Field(alias="notEqualTo", default=None)
    "Matches tags that do not equal the provided value. The key and value are both matched exactly."
    not_in: Optional[list["TagMatchInput"]] = Field(alias="notIn", default=None)
    "Matches tags that do not match any of the provided values. The key and value are both matched exactly. Limited to 100 items maximum."
    not_key_equal_to: Optional[Any] = Field(alias="notKeyEqualTo", default=None)
    "Matches tags where the key does not equal the provided value."
    not_key_in: Optional[list[Any]] = Field(alias="notKeyIn", default=None)
    "Matches tags where the key does not match any of the provided values. Limited to 100 items maximum."


class TagMatchInput(BaseModel):
    """Specifies a single tag that an entity is expected to have. You must specify both the key and the value."""

    key: Any
    "The key of this tag."
    value: Any
    "The value associated with this tag's key."


class TxMatchInput(BaseModel):
    """Specify a Tx by using `id` or `externalId`, the Link it belongs to by `linkId`, and the External Account it is a part of by `accountId` or `externalAccountId`."""

    account_id: Optional[str] = Field(alias="accountId", default=None)
    "The FRAGMENT ID of the external account"
    external_account_id: Optional[str] = Field(alias="externalAccountId", default=None)
    "The external system's ID for the account"
    external_id: Optional[str] = Field(alias="externalId", default=None)
    "The external system's ID for the transaction"
    id: Optional[str] = None
    "The FRAGMENT ID of the transaction"
    link_id: Optional[str] = Field(alias="linkId", default=None)
    "The FRAGMENT ID of the link"


class TxTypeFilter(BaseModel):
    equal_to: Optional[TxType] = Field(alias="equalTo", default=None)
    in_: Optional[list[TxType]] = Field(alias="in", default=None)
    "Must match one of the values provided. Limited to 100 items maximum."


class UpdateLedgerAccountInput(BaseModel):
    consistency_config: Optional["LedgerAccountConsistencyConfigInput"] = Field(
        alias="consistencyConfig", default=None
    )
    "The consistency configuration for this ledger account. This defines how updates to this ledger account's balance are handled."
    name: Optional[str] = None
    "The name to update the ledger account to"


class UpdateLedgerEntryInput(BaseModel):
    groups: Optional[list["LedgerEntryGroupInput"]] = None
    "The list of Groups to add to this Ledger Entry."
    ledger_lines: Optional[list["UpdateLedgerLineInput"]] = Field(
        alias="ledgerLines", default=None
    )
    "The list of Ledger Line updates to apply to Ledger Lines on this Ledger Entry."
    tags: Optional[list["LedgerEntryTagInput"]] = None
    "The list of Tags to add and/or update on this Ledger Entry."
    tags_to_remove: Optional[list["LedgerEntryTagInput"]] = Field(
        alias="tagsToRemove", default=None
    )
    "The list of Tags to remove from this Ledger Entry."


class UpdateLedgerInput(BaseModel):
    name: Optional[str] = None
    "The new Ledger name. "


class UpdateLedgerLineInput(BaseModel):
    ledger_line: "LedgerLineMatchInput" = Field(alias="ledgerLine")
    "The Ledger Line that is being updated. It must belong to the Ledger Entry being updated."
    tags: Optional[list["LedgerLineTagInput"]] = None
    "The list of Tags to add and/or update on this Ledger Line."
    tags_to_remove: Optional[list["LedgerLineTagInput"]] = Field(
        alias="tagsToRemove", default=None
    )
    "The list of Tags to remove from this Ledger Line."


AddLedgerEntryInput.model_rebuild()
ChartOfAccountsInput.model_rebuild()
CreateLedgerAccountInput.model_rebuild()
CreateLedgerAccountsInput.model_rebuild()
CurrencyFilter.model_rebuild()
CustomAccountInput.model_rebuild()
CustomTxInput.model_rebuild()
ExternalAccountFilter.model_rebuild()
GroupBalanceAccountFilter.model_rebuild()
GroupFilter.model_rebuild()
GroupInput.model_rebuild()
GroupReconciliationParametersInput.model_rebuild()
LedgerAccountConditionInput.model_rebuild()
LedgerAccountConsistencyConfigInput.model_rebuild()
LedgerAccountDataMigrationsFilterSet.model_rebuild()
LedgerAccountFilter.model_rebuild()
LedgerAccountMatchInput.model_rebuild()
LedgerAccountsFilterSet.model_rebuild()
LedgerEntriesFilterSet.model_rebuild()
LedgerEntryConditionInput.model_rebuild()
LedgerEntryDataMigrationsFilterSet.model_rebuild()
LedgerEntryFilter.model_rebuild()
LedgerEntryGroupBalanceFilter.model_rebuild()
LedgerEntryGroupBalanceFilterSet.model_rebuild()
LedgerEntryGroupMatchInput.model_rebuild()
LedgerEntryGroupsFilterSet.model_rebuild()
LedgerEntryInput.model_rebuild()
LedgerEntryMatchInput.model_rebuild()
LedgerLineInput.model_rebuild()
LedgerLinesFilterSet.model_rebuild()
LedgersFilterSet.model_rebuild()
MigrateLedgerEntryInput.model_rebuild()
SceneEventInput.model_rebuild()
SceneInput.model_rebuild()
SchemaConditionInput.model_rebuild()
SchemaInput.model_rebuild()
SchemaLedgerAccountInput.model_rebuild()
SchemaLedgerEntriesInput.model_rebuild()
SchemaLedgerEntryConditionInput.model_rebuild()
SchemaLedgerEntryInput.model_rebuild()
SchemaLedgerLineInput.model_rebuild()
SchemaPaymentAccountingInput.model_rebuild()
SchemaPaymentEntryInput.model_rebuild()
SchemaPaymentLineInput.model_rebuild()
SchemaPaymentTypeInput.model_rebuild()
SchemaPaymentsInput.model_rebuild()
TagFilter.model_rebuild()
UpdateLedgerAccountInput.model_rebuild()
UpdateLedgerEntryInput.model_rebuild()
UpdateLedgerLineInput.model_rebuild()
