# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Optional

from pydantic import Field

from .base_model import BaseModel


class ListLedgerEntries(BaseModel):
    ledger: Optional["ListLedgerEntriesLedger"]


class ListLedgerEntriesLedger(BaseModel):
    ledger_entries: "ListLedgerEntriesLedgerLedgerEntries" = Field(
        alias="ledgerEntries"
    )


class ListLedgerEntriesLedgerLedgerEntries(BaseModel):
    nodes: list["ListLedgerEntriesLedgerLedgerEntriesNodes"]
    page_info: "ListLedgerEntriesLedgerLedgerEntriesPageInfo" = Field(alias="pageInfo")


class ListLedgerEntriesLedgerLedgerEntriesNodes(BaseModel):
    ik: str
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    lines: "ListLedgerEntriesLedgerLedgerEntriesNodesLines"


class ListLedgerEntriesLedgerLedgerEntriesNodesLines(BaseModel):
    nodes: list["ListLedgerEntriesLedgerLedgerEntriesNodesLinesNodes"]


class ListLedgerEntriesLedgerLedgerEntriesNodesLinesNodes(BaseModel):
    amount: Any
    account: "ListLedgerEntriesLedgerLedgerEntriesNodesLinesNodesAccount"


class ListLedgerEntriesLedgerLedgerEntriesNodesLinesNodesAccount(BaseModel):
    path: str


class ListLedgerEntriesLedgerLedgerEntriesPageInfo(BaseModel):
    has_next_page: bool = Field(alias="hasNextPage")
    end_cursor: Optional[str] = Field(alias="endCursor")
    has_previous_page: bool = Field(alias="hasPreviousPage")
    start_cursor: Optional[str] = Field(alias="startCursor")


ListLedgerEntries.model_rebuild()
ListLedgerEntriesLedger.model_rebuild()
ListLedgerEntriesLedgerLedgerEntries.model_rebuild()
ListLedgerEntriesLedgerLedgerEntriesNodes.model_rebuild()
ListLedgerEntriesLedgerLedgerEntriesNodesLines.model_rebuild()
ListLedgerEntriesLedgerLedgerEntriesNodesLinesNodes.model_rebuild()
