# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostOrderPlaced(BaseModel):
    add_ledger_entry: Union[
        "PostOrderPlacedAddLedgerEntryAddLedgerEntryResult",
        "PostOrderPlacedAddLedgerEntryBadRequestError",
        "PostOrderPlacedAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list["PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntryGroups"]


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional["PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLinesCurrency"]
    key: Optional[str]


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLinesAccount(BaseModel):
    path: str


class PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLinesCurrency(BaseModel):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostOrderPlacedAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostOrderPlacedAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostOrderPlaced.model_rebuild()
PostOrderPlacedAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostOrderPlacedAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostOrderPlacedAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
