# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostDriverPayoutInitiate(BaseModel):
    add_ledger_entry: Union[
        "PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResult",
        "PostDriverPayoutInitiateAddLedgerEntryBadRequestError",
        "PostDriverPayoutInitiateAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list[
        "PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryGroups"
    ]


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional[
        "PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesAccount(BaseModel):
    path: str


class PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesCurrency(
    BaseModel
):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostDriverPayoutInitiateAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostDriverPayoutInitiateAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostDriverPayoutInitiate.model_rebuild()
PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostDriverPayoutInitiateAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
