# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostDisputePayoutInitiate(BaseModel):
    add_ledger_entry: Union[
        "PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResult",
        "PostDisputePayoutInitiateAddLedgerEntryBadRequestError",
        "PostDisputePayoutInitiateAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list[
        "PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryGroups"
    ]


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional[
        "PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesAccount(
    BaseModel
):
    path: str


class PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesCurrency(
    BaseModel
):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostDisputePayoutInitiateAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostDisputePayoutInitiateAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostDisputePayoutInitiate.model_rebuild()
PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostDisputePayoutInitiateAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
