# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostDisputePayoutSettle(BaseModel):
    add_ledger_entry: Union[
        "PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResult",
        "PostDisputePayoutSettleAddLedgerEntryBadRequestError",
        "PostDisputePayoutSettleAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list["PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntryGroups"]


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional[
        "PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLinesAccount(BaseModel):
    path: str


class PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency(BaseModel):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostDisputePayoutSettleAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostDisputePayoutSettleAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostDisputePayoutSettle.model_rebuild()
PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostDisputePayoutSettleAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
