# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostRestaurantPayoutSettle(BaseModel):
    add_ledger_entry: Union[
        "PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResult",
        "PostRestaurantPayoutSettleAddLedgerEntryBadRequestError",
        "PostRestaurantPayoutSettleAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list[
        "PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryGroups"
    ]


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryLedger(
    BaseModel
):
    ik: Any


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryGroups(
    BaseModel
):
    key: Any
    value: Any


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional[
        "PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesAccount(
    BaseModel
):
    path: str


class PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency(
    BaseModel
):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostRestaurantPayoutSettleAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostRestaurantPayoutSettleAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostRestaurantPayoutSettle.model_rebuild()
PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostRestaurantPayoutSettleAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
