# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostDriverPayoutSettle(BaseModel):
    add_ledger_entry: Union[
        "PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResult",
        "PostDriverPayoutSettleAddLedgerEntryBadRequestError",
        "PostDriverPayoutSettleAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list["PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryGroups"]


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional[
        "PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesAccount(BaseModel):
    path: str


class PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency(BaseModel):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostDriverPayoutSettleAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostDriverPayoutSettleAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostDriverPayoutSettle.model_rebuild()
PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostDriverPayoutSettleAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
