# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostCardSettle(BaseModel):
    add_ledger_entry: Union[
        "PostCardSettleAddLedgerEntryAddLedgerEntryResult",
        "PostCardSettleAddLedgerEntryBadRequestError",
        "PostCardSettleAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostCardSettleAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostCardSettleAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostCardSettleAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostCardSettleAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostCardSettleAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostCardSettleAddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list["PostCardSettleAddLedgerEntryAddLedgerEntryResultEntryGroups"]


class PostCardSettleAddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostCardSettleAddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostCardSettleAddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostCardSettleAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostCardSettleAddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional["PostCardSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency"]
    key: Optional[str]


class PostCardSettleAddLedgerEntryAddLedgerEntryResultLinesAccount(BaseModel):
    path: str


class PostCardSettleAddLedgerEntryAddLedgerEntryResultLinesCurrency(BaseModel):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostCardSettleAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostCardSettleAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostCardSettle.model_rebuild()
PostCardSettleAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostCardSettleAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostCardSettleAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
