# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostOrderPlacedV2(BaseModel):
    add_ledger_entry: Union[
        "PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResult",
        "PostOrderPlacedV2AddLedgerEntryBadRequestError",
        "PostOrderPlacedV2AddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list["PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntryTags"]
    groups: list["PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntryGroups"]


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntryLedger(BaseModel):
    ik: Any


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntryTags(BaseModel):
    key: Any
    value: Any


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntryGroups(BaseModel):
    key: Any
    value: Any


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: "PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLinesAccount"
    amount: Any
    currency: Optional[
        "PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLinesAccount(BaseModel):
    path: str


class PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLinesCurrency(BaseModel):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostOrderPlacedV2AddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostOrderPlacedV2AddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostOrderPlacedV2.model_rebuild()
PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostOrderPlacedV2AddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
