# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import CurrencyCode


class PostRestaurantPayoutInitiate(BaseModel):
    add_ledger_entry: Union[
        "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResult",
        "PostRestaurantPayoutInitiateAddLedgerEntryBadRequestError",
        "PostRestaurantPayoutInitiateAddLedgerEntryInternalError",
    ] = Field(alias="addLedgerEntry", discriminator="typename__")


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResult(BaseModel):
    typename__: Literal["AddLedgerEntryResult"] = Field(alias="__typename")
    entry: "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry"
    lines: list["PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLines"]
    is_ik_replay: bool = Field(alias="isIkReplay")


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry(BaseModel):
    ik: str
    id: str
    created: Any
    type_: Optional[Any] = Field(alias="type")
    posted: Any
    description: Optional[str]
    ledger: "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryLedger"
    tags: list[
        "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryTags"
    ]
    groups: list[
        "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryGroups"
    ]


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryLedger(
    BaseModel
):
    ik: Any


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryTags(
    BaseModel
):
    key: Any
    value: Any


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntryGroups(
    BaseModel
):
    key: Any
    value: Any


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLines(BaseModel):
    account: (
        "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesAccount"
    )
    amount: Any
    currency: Optional[
        "PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesCurrency"
    ]
    key: Optional[str]


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesAccount(
    BaseModel
):
    path: str


class PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLinesCurrency(
    BaseModel
):
    code: CurrencyCode
    custom_currency_id: Optional[Any] = Field(alias="customCurrencyId")


class PostRestaurantPayoutInitiateAddLedgerEntryBadRequestError(BaseModel):
    typename__: Literal["BadRequestError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


class PostRestaurantPayoutInitiateAddLedgerEntryInternalError(BaseModel):
    typename__: Literal["InternalError"] = Field(alias="__typename")
    code: str
    message: str
    retryable: bool


PostRestaurantPayoutInitiate.model_rebuild()
PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResult.model_rebuild()
PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultEntry.model_rebuild()
PostRestaurantPayoutInitiateAddLedgerEntryAddLedgerEntryResultLines.model_rebuild()
