# Generated by fragment (with the help of ariadne-codegen)
# Source: tests/snapshots/001-marketing-schema/

from typing import Any, ClassVar, Dict, List, Optional, Sequence

from pydantic import model_serializer

from .base_model import BaseModel
from .input_types import (
    AddLedgerEntryInput,
    LedgerEntryConditionInput,
    LedgerEntryGroupInput,
    LedgerEntryInput,
    LedgerEntryTagInput,
    LedgerMatchInput,
)


class TypedLedgerEntry(BaseModel):
    """Base class for a strongly-typed `addLedgerEntries` payload.

    Subclasses declare one field per Schema parameter. The serializer below
    reshapes those flat fields into the nested `AddLedgerEntryInput` the API
    expects, so instances can be passed to `add_ledger_entries` directly.

    That makes dumping one-way: `model_dump()` returns the `AddLedgerEntryInput`
    shape rather than this model's own fields, so
    `type(entry).model_validate(entry.model_dump())` does not round-trip. Dumps
    are for sending; keep the instance itself if you need to log or cache one.
    """

    ENTRY_TYPE: ClassVar[str] = ""
    TYPE_VERSION: ClassVar[int] = 1
    # Maps Schema parameter name -> Python field name. These differ only when a
    # parameter is camelCased or collides with a field on this class.
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {}

    ik: Any
    ledger_ik: Any
    description: Optional[str] = None
    posted: Optional[Any] = None
    tags: Optional[List[LedgerEntryTagInput]] = None
    groups: Optional[List[LedgerEntryGroupInput]] = None
    conditions: Optional[List[LedgerEntryConditionInput]] = None

    def entry_parameters(self) -> Dict[str, Any]:
        """The `parameters` payload, keyed by Schema parameter name."""
        return {
            parameter_name: getattr(self, field_name)
            for parameter_name, field_name in self.PARAMETER_FIELDS.items()
            if getattr(self, field_name) is not None
        }

    def to_input(self) -> AddLedgerEntryInput:
        """Convert to the `AddLedgerEntryInput` that `addLedgerEntries` takes."""
        return AddLedgerEntryInput(
            ik=self.ik,
            entry=LedgerEntryInput(
                ledger=LedgerMatchInput(ik=self.ledger_ik),
                type=self.ENTRY_TYPE,
                typeVersion=self.TYPE_VERSION,
                parameters=self.entry_parameters(),
                description=self.description,
                posted=self.posted,
                tags=self.tags,
                groups=self.groups,
                conditions=self.conditions,
            ),
        )

    @model_serializer
    def serialize(self) -> Dict[str, Any]:
        """Serialize as `AddLedgerEntryInput`, not as this flat model.

        The base client dumps variables with `model_dump(by_alias=True)`, so
        this is what puts the correct shape on the wire.
        """
        return self.to_input().model_dump(by_alias=True, exclude_none=True)


def to_entry_inputs(
    entries: Sequence[TypedLedgerEntry],
) -> List[AddLedgerEntryInput]:
    """Convert typed entries to raw inputs, preserving order.

    `add_ledger_entries` accepts typed entries directly. This is for callers who
    want to inspect or adjust the raw payload first.
    """
    return [entry.to_input() for entry in entries]


class CardSettleV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "card_settle" Ledger Entry.

    Derived from the `PostCardSettle` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "card_settle"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "user_id": "user_id",
        "order_id": "order_id",
        "currency": "currency",
        "amount": "amount",
    }

    user_id: str
    order_id: str
    currency: str
    amount: str


class DisputePayoutInitiateV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "dispute_payout_initiate" Ledger Entry.

    Derived from the `PostDisputePayoutInitiate` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "dispute_payout_initiate"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "user_id": "user_id",
        "disputes_id": "disputes_id",
        "amount": "amount",
        "currency": "currency",
        "payout_id": "payout_id",
        "order_id": "order_id",
    }

    user_id: str
    disputes_id: str
    amount: str
    currency: str
    payout_id: str
    order_id: str


class DisputePayoutSettleV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "dispute_payout_settle" Ledger Entry.

    Derived from the `PostDisputePayoutSettle` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "dispute_payout_settle"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "user_id": "user_id",
        "disputes_id": "disputes_id",
        "amount": "amount",
        "currency": "currency",
        "order_id": "order_id",
    }

    user_id: str
    disputes_id: str
    amount: str
    currency: str
    order_id: str


class DriverPayoutInitiateV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "driver_payout_initiate" Ledger Entry.

    Derived from the `PostDriverPayoutInitiate` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "driver_payout_initiate"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "driver_id": "driver_id",
        "order_id": "order_id",
        "currency": "currency",
        "amount": "amount",
        "payout_id": "payout_id",
    }

    driver_id: str
    order_id: str
    currency: str
    amount: str
    payout_id: str


class DriverPayoutSettleV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "driver_payout_settle" Ledger Entry.

    Derived from the `PostDriverPayoutSettle` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "driver_payout_settle"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "driver_id": "driver_id",
        "payout_id": "payout_id",
        "currency": "currency",
        "amount": "amount",
    }

    driver_id: str
    payout_id: str
    currency: str
    amount: str


class OrderPlacedV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "order_placed" Ledger Entry.

    Derived from the `PostOrderPlaced` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "order_placed"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "user_id": "user_id",
        "order_id": "order_id",
        "order_cost": "order_cost",
        "currency": "currency",
        "platform_fee": "platform_fee",
        "driver_fee": "driver_fee",
        "restaurant_id": "restaurant_id",
        "driver_id": "driver_id",
    }

    user_id: str
    order_id: str
    order_cost: str
    currency: str
    platform_fee: str
    driver_fee: str
    restaurant_id: str
    driver_id: str


class OrderPlacedV2(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "order_placed" Ledger Entry.

    Derived from the `PostOrderPlaced_v2` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "order_placed"
    TYPE_VERSION: ClassVar[int] = 2
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "user_id": "user_id",
        "order_id": "order_id",
        "order_cost": "order_cost",
        "currency": "currency",
        "platform_fee": "platform_fee",
        "service_fee": "service_fee",
        "driver_fee": "driver_fee",
        "restaurant_id": "restaurant_id",
        "driver_id": "driver_id",
    }

    user_id: str
    order_id: str
    order_cost: str
    currency: str
    platform_fee: str
    service_fee: str
    driver_fee: str
    restaurant_id: str
    driver_id: str


class RestaurantPayoutInitiateV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "restaurant_payout_initiate" Ledger Entry.

    Derived from the `PostRestaurantPayoutInitiate` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "restaurant_payout_initiate"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "restaurant_id": "restaurant_id",
        "order_id": "order_id",
        "currency": "currency",
        "amount": "amount",
        "payout_id": "payout_id",
    }

    restaurant_id: str
    order_id: str
    currency: str
    amount: str
    payout_id: str


class RestaurantPayoutSettleV1(TypedLedgerEntry):
    """Typed `addLedgerEntries` payload for the "restaurant_payout_settle" Ledger Entry.

    Derived from the `PostRestaurantPayoutSettle` operation.
    """

    ENTRY_TYPE: ClassVar[str] = "restaurant_payout_settle"
    TYPE_VERSION: ClassVar[int] = 1
    PARAMETER_FIELDS: ClassVar[Dict[str, str]] = {
        "restaurant_id": "restaurant_id",
        "payout_id": "payout_id",
        "currency": "currency",
        "amount": "amount",
    }

    restaurant_id: str
    payout_id: str
    currency: str
    amount: str
