name: Create Release
on:
  workflow_dispatch:
    inputs:
      type:
        type: choice
        description: Release Type
        options:
        - patch
        - minor
        - major

jobs:
  createRelease:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: tibdex/github-app-token@32691ba7c9e7063bd457bd8f2a5703138591fa58 # v1
        id: generate-token
        with:
          app_id: ${{ secrets.PR_APP_ID }}
          private_key: ${{ secrets.PR_APP_PRIVATE_KEY }}

      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        name: Checkout fragment-python

      - name: Use Python 3.10.14
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: '3.10.14'

      - name: Install dependencies
        run: |
          pip install poetry
          poetry install --with dev

      - name: Bump version
        id: bump-version
        run: |
          poetry version ${{ inputs.type }}
          echo "version=$(poetry version -s)" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@153407881ec5c347639a548ade7d8ad1d6740e38 # v4
        with:
          token: ${{ steps.generate-token.outputs.token }}
          commit-message: 'Update Python SDK queries'
          title: 'Update Python SDK queries ${{ steps.bump-version.outputs.version }}'
          base: 'dev'
          branch: update-sdk-queries/${{ steps.bump-version.outputs.version }}
          body: >
            This PR is auto-generated by github action.
